# Generated by Django 6.0.5 on 2026-05-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '__first__'),
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=50)),
                ('activity_type', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('electricity_purchased', 'Purchased Electricity'), ('business_travel_flight', 'Business Travel - Flight'), ('business_travel_hotel', 'Business Travel - Hotel'), ('business_travel_ground', 'Business Travel - Ground Transport'), ('procurement', 'Procurement')], max_length=30)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 - Direct'), ('scope_2', 'Scope 2 - Indirect Energy'), ('scope_3', 'Scope 3 - Indirect Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('activity_date', models.DateField()),
                ('billing_start_date', models.DateField(blank=True, null=True)),
                ('billing_end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('flagged', 'Flagged for Review'), ('approved', 'Approved'), ('locked', 'Locked for Audit')], default='pending_review', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('original_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='tenants.company')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='ingestion.ingestionjob')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_record', to='ingestion.rawrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('locked', 'Locked')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='normalization.activityrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousFlagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('fuel_combustion', 'Fuel Combustion'), ('electricity_purchased', 'Purchased Electricity'), ('business_travel_flight', 'Business Travel - Flight'), ('business_travel_hotel', 'Business Travel - Hotel'), ('business_travel_ground', 'Business Travel - Ground Transport'), ('procurement', 'Procurement')], max_length=30)),
                ('field_name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('eq', 'Equal to'), ('missing', 'Missing')], max_length=20)),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_rules', to='tenants.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['company', 'status'], name='normalizati_company_6a95c0_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['company', 'scope'], name='normalizati_company_3b286e_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['activity_date'], name='normalizati_activit_decab8_idx'),
        ),
    ]
